export const items = [
  {
    id: 'Cqwvw7DzCOkvJHHoIL1zhW54',
    name: 'Table',
    price: '135.00',
    category: '',
  },
  {
    id: 'cGGYDzDbrWhpKzMwvS4LwtgD',
    name: 'Cheese',
    price: '636.00',
    category: '',
  },
  {
    id: 'cU63qwKooV2zWoVgzzGR1vpu',
    name: 'Tuna',
    price: '194.00',
    category: '',
  },
  {
    id: 'UCzzfQ9DHsWmQRyUSRw8K4uX',
    name: 'Bacon',
    price: '667.00',
    category: '',
  },
  {
    id: 'NCFNCqeDI0vzcn54EHEeUqL6',
    name: 'Mouse',
    price: '556.00',
    category: '',
  },
  {
    id: '6kb0shOaBavXYdQJqdKspkf3',
    name: 'Bacon',
    price: '103.00',
    category: '',
  },
  {
    id: 'dikcRNJhF0AgZhynXSGgZXCB',
    name: 'Pizza',
    price: '244.00',
    category: '',
  },
  {
    id: 'qT6Squb1WWPBLG7mHXX0PDtw',
    name: 'Shoes',
    price: '258.00',
    category: '',
  },
  {
    id: 'LTJ7yGLaT4CtVAtcdq6SOr9f',
    name: 'Shirt',
    price: '957.00',
    category: '',
  },
  {
    id: 'nbwznWcHsdztBwaQYlBq1Hzh',
    name: 'Bacon',
    price: '150.00',
    category: '',
  },
  {
    id: 'lN8SzCUSQa5XFpLOORsm2pVA',
    name: 'Chicken',
    price: '570.00',
    category: '',
  },
  {
    id: 'TKvrLAf1ObF38Jg2jdCLopHZ',
    name: 'Bike',
    price: '951.00',
    category: '',
  },
  {
    id: 'Gpa52WEdifyiDyJXuWBgAirh',
    name: 'Salad',
    price: '672.00',
    category: '',
  },
  {
    id: 'muuqD9czaO0vPMAjqKP7wSIa',
    name: 'Computer',
    price: '901.00',
    category: '',
  },
  {
    id: '19XvtoLT2OU61AfG4qNH3cWO',
    name: 'Keyboard',
    price: '725.00',
    category: '',
  },
  {
    id: 'A2hLPuqttWWkrEdqBuVqD4VL',
    name: 'Pants',
    price: '463.00',
    category: '',
  },
  {
    id: 'qhKutCvjINJv0iif0EjTROtM',
    name: 'Tuna',
    price: '780.00',
    category: '',
  },
  {
    id: 'zws8q6tjVTmvHCsT4A7kWwfa',
    name: 'Pizza',
    price: '928.00',
    category: '',
  },
  {
    id: 'LrcncLnZ9WXazZM0K66iFRAn',
    name: 'Keyboard',
    price: '717.00',
    category: '',
  },
  {
    id: 'mXcf0vBXXyoOo8bcGOXE8vH8',
    name: 'Bike',
    price: '727.00',
    category: '',
  },
  {
    id: 'pPOZh7tGEzN1yCkMIk0kULvb',
    name: 'Keyboard',
    price: '333.00',
    category: '',
  },
  {
    id: 'i69lzjbZ7utyZt4zOClmrMCV',
    name: 'Bacon',
    price: '312.00',
    category: '',
  },
  {
    id: '4jnMF4HbokM9TbQlE1Mkmrzz',
    name: 'Cheese',
    price: '953.00',
    category: '',
  },
  {
    id: 'Fm7i4f3Y4zPLTcv0Xf5ACV3C',
    name: 'Computer',
    price: '957.00',
    category: '',
  },
  {
    id: '3M19ruad43i34LSH7vCsO8Vd',
    name: 'Ball',
    price: '316.00',
    category: '',
  },
  {
    id: 'zctwwc4KGVVj6rLeiVvG19VV',
    name: 'Gloves',
    price: '128.00',
    category: '',
  },
  {
    id: 'iMpd2oa4JLoDcCOe9BqiPb8O',
    name: 'Tuna',
    price: '727.00',
    category: '',
  },
  {
    id: 'WRqqQS7AN79T2TnLvr0Fb6Hl',
    name: 'Cheese',
    price: '264.00',
    category: '',
  },
  {
    id: 'nzJPn3JA7RSelpK4VH7io0DB',
    name: 'Chips',
    price: '906.00',
    category: '',
  },
  { id: 'unjolwTg2VkXw1UY5Boq16Qg', name: 'Car', price: '98.00', category: '' },
  {
    id: 'hbaHfAgKXB99hpcrt9RU29OT',
    name: 'Bacon',
    price: '858.00',
    category: '',
  },
  {
    id: 'J6YtEPI2zmPK92A02J3IEwal',
    name: 'Bike',
    price: '135.00',
    category: '',
  },
  {
    id: 'nTDAHPSvqsrvy2YTq4TFC85U',
    name: 'Table',
    price: '191.00',
    category: '',
  },
  {
    id: 'dOFpPfEYDCmPYgCkZIBZAs70',
    name: 'Chicken',
    price: '206.00',
    category: '',
  },
  {
    id: 'DFugsHwPoDqKRrqMFYgj4Qhr',
    name: 'Salad',
    price: '362.00',
    category: '',
  },
  {
    id: 'ACZkpJOhPNofcIeQdec4KIZI',
    name: 'Car',
    price: '755.00',
    category: '',
  },
  {
    id: 'bgC0NcbiUr7h0OP4Xq0aA9wz',
    name: 'Mouse',
    price: '476.00',
    category: '',
  },
  {
    id: 'PTrbR46EBd6BZPnzIk2bR9C1',
    name: 'Ball',
    price: '578.00',
    category: '',
  },
  {
    id: 'PWkIdl9zT8FetqA5NzJRoAgE',
    name: 'Chips',
    price: '207.00',
    category: '',
  },
  {
    id: 'zXn9WnHzSwcmVRPySczIVk93',
    name: 'Hat',
    price: '626.00',
    category: '',
  },
  {
    id: 'FkyHeBacS8OUCVvhlyNZfeBG',
    name: 'Pizza',
    price: '852.00',
    category: '',
  },
  {
    id: 'XboYoIGqEeV0Su9O8WnWD465',
    name: 'Ball',
    price: '567.00',
    category: '',
  },
  {
    id: 'jHzXuA0aAYPYZeoSXB2yMeHz',
    name: 'Sausages',
    price: '706.00',
    category: '',
  },
  {
    id: 'ziazMzTa8LtkB7S7MSsERuep',
    name: 'Table',
    price: '468.00',
    category: '',
  },
  {
    id: 'KfBZq9lfs6GW0SZLXbQTR6Q4',
    name: 'Chair',
    price: '935.00',
    category: '',
  },
  {
    id: 'fAH2JUNzh3ICzQ39Wih8T9c8',
    name: 'Chicken',
    price: '720.00',
    category: '',
  },
  {
    id: 'eP8yieHDtHjgRVMMutBSPz8v',
    name: 'Cheese',
    price: '825.00',
    category: '',
  },
  {
    id: 'LsAYWN0vON0dvOCzmsezV9qB',
    name: 'Pants',
    price: '210.00',
    category: '',
  },
  {
    id: 'It9J6bOtWIIPw0oHKh9d8VMH',
    name: 'Towels',
    price: '987.00',
    category: '',
  },
  {
    id: 'TPiRCcLXOBV4ZWabzvPchzgz',
    name: 'Chair',
    price: '479.00',
    category: '',
  },
]
